CLASSPATH=${JDKZIP}:${JXLIBS}/zero:${JXLIBS}/zero_misc:${JXLIBS}/classfile:${JXLIBS}/collections:${JXLIBS}/classstore:${JXLIBS}/zip:${JXLIBS}/compspec:${JXLIBS}/compiler:${JXLIBS}/bootrc:${JXEDOMAINS}/compspec:${JXEMULATION}

all:
	cd jx/compspec; $(MAKE) CLASSPATH=$(CLASSPATH) compile

clean:
	cd jx/compspec; $(MAKE) clean
