CLASSPATH=${JDKZIP}:${JXLIBS}/zero:${JXLIBS}/zero_misc:${JXLIBS}/classfile:${JXLIBS}/collections:${JXLIBS}/classstore:${JXLIBS}/zip:${JXLIBS}/statistics:${JXLIBS}/compiler:${JXEDOMAINS}/statistics:${JXEMULATION}

all:
	cd jx/statistics; $(MAKE) CLASSPATH=$(CLASSPATH) compile

clean:
	cd jx/statistics; $(MAKE) clean
